CREATE TABLE IF NOT EXISTS Person (
	id SERIAL PRIMARY KEY, 
	PersonName VARCHAR NOT NULL,
	Department INTEGER NOT NULL,
	Chief_ID INTEGER NOT NULL
);

CREATE TABLE IF NOT EXISTS Chief (
	id SERIAL PRIMARY KEY, 
	ChiefName  VARCHAR NOT NULL,
	Department INTEGER NOT NULL,
	Subordinate INTEGER NOT NULL REFERENCES Person(ID)
);

CREATE TABLE IF NOT EXISTS Department (
	id SERIAL PRIMARY KEY, 
	DepartmentName VARCHAR NOT NULL
);

